[platformio]
default_envs = esp32-s3-devkitc-1
src_dir = device/src

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -D CORE_DEBUG_LEVEL=1
  -D FREE_ALEXANDRIA_AP_SSID=\"Free_Alexandria\"
  -D FREE_ALEXANDRIA_HOSTNAME=\"free-alexandria\"
lib_deps =
  ottowinter/ESPAsyncWebServer-esphome@^3.3.0
  ottowinter/AsyncTCP-esphome@^2.1.4
